# Minimal makefile for Sphinx documentation

.PHONY: help clean html

help:
	@echo "make html    to build HTML docs"
	@echo "make clean   to clean build"

clean:
	rm -rf _build

html:
	sphinx-build -b html . _build
